#!/usr/bin/env perl

use strict;
use File::Find;
use Cwd;
my $dir = getcwd;

my $delete = 0;
my $time = 0;
my $iter = 0;
my $num = 0;
my $namegiven = 0;
my $name = "";
foreach $num (0 .. $#ARGV) {
	if ($ARGV[$num] =~ m/-d/i) {
	    print "delete after cat\n";
	    $delete = 1;
	}
	if ($ARGV[$num] =~ m/-t/i) {
	    print "merge time\n";
	    $time = 1;
	}
	if ($ARGV[$num] =~ m/-i/i) {
	    print "merge iterations\n";
	    $iter = 1;
	}
	if ($ARGV[$num-1] =~ m/-n/i) {
	    $namegiven = 1;
	    $name = $ARGV[$num];
	}
}
if (!$delete) {
    print "not deleting after cat\n";
}

#my $dir = shift || die "Argument missing: directory name\n";
#find( sub {print "$File::Find::name$/" if (/.-P0./)},$dir);
my @files = ();
my @file_classes = ();

find(sub {push @files, $File::Find::name if(/$name-P0.*/);} ,"$dir"); #custom subroutine find, parse $dir

foreach (@files) {
    my $catname = $_;
    my $globname = $_;
    $globname =~ s/-P0/-P\*/;
    $catname =~ s/-P0//;
    system("cat $globname > $catname");
    # if ($delete) {        
        system("rm $globname");
    # }
}

if ($time) 
{
    my @files = ();
    my @file_classes = ();
    find(\&find_classes,"$dir"); #custom subroutine find, parse $dir


    # following gets called recursively for each file in $dir, check $_ to see if you want the file!
    sub find_classes()
    {
        my $alreadyFound = 0;
        if ($_ =~ m/(.*)-(time_[0-9]+([_e]-?[0-9]+)?)(.*\.plt)$/) {
            push @files, $_;
            # print "$1   $2  $4\n";
            foreach (@file_classes) {
                if ($_ =~ m/$1/ && !($_ =~ m/merged-time/)) {
                    $alreadyFound = 1;
                }
            }
            if (!$alreadyFound) {
                push @file_classes, "$1*$4" 
            }
        }
    }

    foreach(@file_classes) {
        my $catname = $_;
        my $globname = $_;
        $catname =~ s/\*/-merged-time/;
        system("cat $globname > $catname");
    }

    if ($delete) {
        foreach(@files) {
            system("rm $_");
        }  
    }
}

if ($iter) 
{
    my @files = ();
    my @file_classes = ();
    find(\&find_classes,"$dir"); #custom subroutine find, parse $dir


    # following gets called recursively for each file in $dir, check $_ to see if you want the file!
    sub find_classes()
    {
        my $alreadyFound = 0;
        if ($_ =~ m/(.*)-(iter_[0-9]+)(.*\.plt)$/) {
            push @files, $_;
            # print "$1   $2  $4\n";
            foreach (@file_classes) {
                if ($_ =~ m/$1/ && !($_ =~ m/merged-iter/)) {
                    $alreadyFound = 1;
                }
            }
            if (!$alreadyFound) {
                push @file_classes, "$1*$3" 
            }
        }
    }

    foreach(@file_classes) {
        my $catname = $_;
        my $globname = $_;
        $catname =~ s/\*/-merged-iter/;
        system("cat $globname > $catname");
    }

    if ($delete) {
        foreach(@files) {
            system("rm $_");
        }  
    }
}


